# Site settings
title: thjorth in the web
email: thjorth74@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is just used for slides, experiments, giggles and whatnot
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thjorth.github.io" # the base hostname & protocol for your site
highlighter: pygments

# Build settings
markdown: kramdown

# defaults
defaults:
  -
    scope:
      path: "front-end-tooling"
      type: "pages"
    values:
      layout: "slide"
      palette: "monster"
      fonts: "https://fonts.googleapis.com/css?family=Bangers|Fjalla+One|Roboto+Condensed:400,300,700"
  -
    scope:
      path: "front-end-build-pipeline"
      type: "pages"
    values:
      layout: "slide"
      palette: "alien"
      fonts: "https://fonts.googleapis.com/css?family=Anton|Bangers|Fjalla+One|Roboto+Condensed:400,300,700"
