# Site settings
title: thjorth in the web
email: thjorth74@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is just used for slides, experiments, giggles and whatnot
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thjorth.github.io" # the base hostname & protocol for your site
highlighter: pygments

# Build settings
markdown: kramdown

# defaults
defaults:
  -
    scope: 
      path: "front-end-tooling"
      type: "pages"
    values:
      layout: "slide"